    <footer role="content-info" id="umbc-footer">
          <div id="umbc-footer-logo" class="first-child"><a href="http://umbc.edu" title="UMBC: An Honors University in Maryland" class="first-child last-child"><span class="first-child last-child">UMBC: An Honors University in Maryland</span></a></div>
          <nav id="umbc-footer-nav">
            <ul id="umbc-footer-nav-items" class="first-child last-child">
              <li class="first-child"><a href="http://about.umbc.edu/" class="first-child last-child">About UMBC</a></li>
              <li><a href="http://about.umbc.edu/visitors-guide/contact-us/" class="first-child last-child">Contact Us</a></li>
              <li><a href="http://umbc.edu/ogc/nondiscrimination.html" class="first-child last-child">Equal Opportunity</a></li>
                        <li class="last-child">Follow UMBC: <a href="https://www.facebook.com/umbcpage" id="umbc-footer-facebook" class="first-child"><span class="none first-child last-child">Facebook</span></a> <a href="http://twitter.com/umbc" id="umbc-footer-twitter"><span class="none first-child last-child">Twitter</span></a> <a href="http://umbc.edu/news" id="umbc-footer-news" class="last-child"><span class="none first-child last-child">UMBC News</span></a></li>
                      </ul>
          </nav>
            <br />
          <div id="umbc-footer-info" class="last-child">&copy; University of Maryland, Baltimore County <span class="bullet first-child">•</span> 1000 Hilltop Circle <span class="bullet last-child">•</span> Baltimore, MD 21250</div>
<p class="hide-on-small-only">This product is meant for educational purposes only. Any resemblance to real persons, living or dead is purely coincidental. Void where prohibited. Some assembly may be required. Batteries not included. Contents may settle during shipment. Use only as directed. May be too intense for some viewers. If condition persists, consult your physician. No user-serviceable parts inside. Breaking seal constitutes acceptance of agreement. Not responsible for direct, indirect, incidental or consequential damages resulting from any defect, error or failure to perform. Slippery when wet. For office use only. Substantial penalty for early withdrawal. Do not write below this line. Your cancelled check is your receipt. Avoid contact with skin. Employees and their families are not eligible. Beware of dog. Driver does not carry cash. Limited time offer, call now to insure prompt delivery. Use only in well-ventilated area. Keep away from fire or flame. Some equipment shown is optional. Price does not include taxes, dealer prep, or delivery. Penalty for private use. Call toll free before digging. Some of the trademarks mentioned in this product appear for identification purposes only. All models over 18 years of age. Do not use while operating a motor vehicle or heavy equipment. Postage will be paid by addressee. Apply only to affected area. One size fits all. Many suitcases look alike. Edited for television. No solicitors. Reproduction strictly prohibited. Restaurant package, not for resale. Objects in mirror are closer than they appear. Decision of judges is final. This supersedes all previous notices. No other warranty expressed or implied.</p>
	    <p>Created with ♥ by <a href="//lin.noblejury.com">Nova</a>.</p>
    </footer>
